/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteRouteImport } from './routes/main/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MainProfitLossRouteImport } from './routes/main/profit-loss'
import { Route as MainProductionRouteImport } from './routes/main/production'
import { Route as MainProcurementRouteImport } from './routes/main/procurement'
import { Route as MainInvoicingRouteImport } from './routes/main/invoicing'
import { Route as MainHrRouteImport } from './routes/main/hr'
import { Route as MainDistributionRouteImport } from './routes/main/distribution'
import { Route as MainDashboardRouteImport } from './routes/main/dashboard'
import { Route as MainAccountingRouteImport } from './routes/main/accounting'

const MainRouteRoute = MainRouteRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainProfitLossRoute = MainProfitLossRouteImport.update({
  id: '/profit-loss',
  path: '/profit-loss',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainProductionRoute = MainProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainProcurementRoute = MainProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainInvoicingRoute = MainInvoicingRouteImport.update({
  id: '/invoicing',
  path: '/invoicing',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainHrRoute = MainHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainDistributionRoute = MainDistributionRouteImport.update({
  id: '/distribution',
  path: '/distribution',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainDashboardRoute = MainDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAccountingRoute = MainAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => MainRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/main': typeof MainRouteRouteWithChildren
  '/main/accounting': typeof MainAccountingRoute
  '/main/dashboard': typeof MainDashboardRoute
  '/main/distribution': typeof MainDistributionRoute
  '/main/hr': typeof MainHrRoute
  '/main/invoicing': typeof MainInvoicingRoute
  '/main/procurement': typeof MainProcurementRoute
  '/main/production': typeof MainProductionRoute
  '/main/profit-loss': typeof MainProfitLossRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/main': typeof MainRouteRouteWithChildren
  '/main/accounting': typeof MainAccountingRoute
  '/main/dashboard': typeof MainDashboardRoute
  '/main/distribution': typeof MainDistributionRoute
  '/main/hr': typeof MainHrRoute
  '/main/invoicing': typeof MainInvoicingRoute
  '/main/procurement': typeof MainProcurementRoute
  '/main/production': typeof MainProductionRoute
  '/main/profit-loss': typeof MainProfitLossRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/main': typeof MainRouteRouteWithChildren
  '/main/accounting': typeof MainAccountingRoute
  '/main/dashboard': typeof MainDashboardRoute
  '/main/distribution': typeof MainDistributionRoute
  '/main/hr': typeof MainHrRoute
  '/main/invoicing': typeof MainInvoicingRoute
  '/main/procurement': typeof MainProcurementRoute
  '/main/production': typeof MainProductionRoute
  '/main/profit-loss': typeof MainProfitLossRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/main'
    | '/main/accounting'
    | '/main/dashboard'
    | '/main/distribution'
    | '/main/hr'
    | '/main/invoicing'
    | '/main/procurement'
    | '/main/production'
    | '/main/profit-loss'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/main'
    | '/main/accounting'
    | '/main/dashboard'
    | '/main/distribution'
    | '/main/hr'
    | '/main/invoicing'
    | '/main/procurement'
    | '/main/production'
    | '/main/profit-loss'
  id:
    | '__root__'
    | '/'
    | '/main'
    | '/main/accounting'
    | '/main/dashboard'
    | '/main/distribution'
    | '/main/hr'
    | '/main/invoicing'
    | '/main/procurement'
    | '/main/production'
    | '/main/profit-loss'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainRouteRoute: typeof MainRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/main': {
      id: '/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main/profit-loss': {
      id: '/main/profit-loss'
      path: '/profit-loss'
      fullPath: '/main/profit-loss'
      preLoaderRoute: typeof MainProfitLossRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/main/production': {
      id: '/main/production'
      path: '/production'
      fullPath: '/main/production'
      preLoaderRoute: typeof MainProductionRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/main/procurement': {
      id: '/main/procurement'
      path: '/procurement'
      fullPath: '/main/procurement'
      preLoaderRoute: typeof MainProcurementRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/main/invoicing': {
      id: '/main/invoicing'
      path: '/invoicing'
      fullPath: '/main/invoicing'
      preLoaderRoute: typeof MainInvoicingRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/main/hr': {
      id: '/main/hr'
      path: '/hr'
      fullPath: '/main/hr'
      preLoaderRoute: typeof MainHrRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/main/distribution': {
      id: '/main/distribution'
      path: '/distribution'
      fullPath: '/main/distribution'
      preLoaderRoute: typeof MainDistributionRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/main/dashboard': {
      id: '/main/dashboard'
      path: '/dashboard'
      fullPath: '/main/dashboard'
      preLoaderRoute: typeof MainDashboardRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/main/accounting': {
      id: '/main/accounting'
      path: '/accounting'
      fullPath: '/main/accounting'
      preLoaderRoute: typeof MainAccountingRouteImport
      parentRoute: typeof MainRouteRoute
    }
  }
}

interface MainRouteRouteChildren {
  MainAccountingRoute: typeof MainAccountingRoute
  MainDashboardRoute: typeof MainDashboardRoute
  MainDistributionRoute: typeof MainDistributionRoute
  MainHrRoute: typeof MainHrRoute
  MainInvoicingRoute: typeof MainInvoicingRoute
  MainProcurementRoute: typeof MainProcurementRoute
  MainProductionRoute: typeof MainProductionRoute
  MainProfitLossRoute: typeof MainProfitLossRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainAccountingRoute: MainAccountingRoute,
  MainDashboardRoute: MainDashboardRoute,
  MainDistributionRoute: MainDistributionRoute,
  MainHrRoute: MainHrRoute,
  MainInvoicingRoute: MainInvoicingRoute,
  MainProcurementRoute: MainProcurementRoute,
  MainProductionRoute: MainProductionRoute,
  MainProfitLossRoute: MainProfitLossRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRouteRoute: MainRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
